"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

module problem002

function solve()
    N = 4e6
    s = b = 2; a = 1; c = 3
    while c <= N
        a = b; b = c; c = a + b
        if c % 2 == 0; s += c; end
    end
    s
end

end
