"""
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first
ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference
are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
"""

module problem044
export main

#= solve 0 = 3/2n^2 - 1/2n - P for n =#
# n = 1/6 ( sqrt(24P + 1) + 1 )
solve_for_n(p) = 1/6*(sqrt(24p + 1) + 1)
function is_pentagonal(x)
    a = solve_for_n(x)
    return abs(a - round(a)) < 1e-12
end

# Solution
function main()
    N = 3000
    min_d = 1e7
    f(n) = 3*n^2/2 - n/2

    for j = 1:N - 1
        a = f(j)
        for k = j + 1:N
            b = f(k)
            if is_pentagonal(a + b) && is_pentagonal(b - a)
                d = abs(a - b)
                if d < min_d
                    min_d = d
                    println("distance is ", d)
                end
            end
        end
    end
end

end
