#!/usr/local/bin/julia

# Problem Statement
println("Triangle, pentagonal, and hexagonal numbers are generated by the")
println("following formulae:")
println()
println("Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...")
println("Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...")
println("Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...")
println("It can be verified that T285 = P165 = H143 = 40755.")
println()
println("Find the next triangle number that is also pentagonal and hexagonal.")

# Solution   
t(n) = (n + 1)/2
p(n) = n*(3*n - 1)/2
h(n) = n*(2*n - 1)

function main()

end

@time main()
